sudo: required
services:
- docker
script:
- echo "1.3" > test1.txt
- pwd && ls
deploy:
  provider: releases
  api_key:
    secure: TZT0xvo1403c4tMY9oARDZspSU5CHG8eYTefZ+UNiTu1sSB1u5Yhfw0VjgUgHG+wGZ2rtiLfWOM7IfVCDQEu0tJVIGWVLzKipprl7bI7v2TnJMUR3kiCkxrbrnOF8YzNUdUuFN6gm0OFmpqWUw3Gdj2DSvp6Je0QLKzUhVG9/s8l+xGMgdef/0wES8QEHbA9EQPO72egTVW5c7lXJTrjTMSw7Qkhi9MqQoJ6Jgm5r2k54goHVHqQguzwVwUcL/Ye5Xv2EA3YxLf17rKI6EQf99cqG2sL6Fc5tiAFaFVuTRJFl9CqT8s1oMEh8bReVVzQljjpPGRxD67n8IBCUCIqX2KDDd6IKQJakAn66vTK1Rz+Dna64MIQ9HFnupZvHKgDCQukmPfrOhTgkBb0n85Ksax2zNtNmX+v/g43ewGZ8Jg7lUGHC9Eh2k5YHWyZaBumj75KAwdAXG6nlI2YHfTO+TBrDOyuImuIgQQmaRwnTjEk9UV8ZbOvqluzSJr+TXkJJ4mmVpWEddvqS4+9fihsg1zP7Q45DJyuEEA//xZGHgeyMwFYGJcegMFqp22fWL60p2Q/Qvfuf/sKsXmF9tsVp6NnuGYi1zQ0GnfudXjOGkIV7+WZ4q0ottZ7dUjxWE8j7mU68iCeV9fBi4EABRg0N5n4Dn1kIfTkTcjqun3KZCU=
  file: test1.txt
  draft: false
  overwrite: true
  skip_cleanup: true
